const imagineRep = {
  "spring" : ["spring_1.jpg","spring_2.jpg","spring_3jpg.jpg","spring_4.jpg","spring_5.jpg"],
  "love" : ["love_1.jpg","love_2.jpg","love_3.jpg","love_4.jpg","love_5.jpg",],
  "history" : ["travel_1.jpg","travel_2.jpg","travel_3.jpg","travel_4.jpg","travel_5.jpg"],
  "death" : ["death_1.jpg","death_2.jpg","death_3.jpg","death_4.jpg","death_5.jpg",]
};
var poemList = {
"Daisy Time" : "See, the grass is full of stars,<br>Fallen in their brightness;<br>Hearts they have of shining gold,<br>Rays of shining whiteness. <br><br>Buttercups have honeyed hearts,<br>Bees they love the clover,<br>But I love the daisies' dance<br>All the meadow over. <br><br>Blow, O blow, you happy winds,<br>Singing summer's praises,<br>Up the field and down the field<br>A-dancing with the daisies. ",
"To Daffodils" : "Fair Daffodils, we weep to see<br>You haste away so soon;<br>As yet the early-rising sun<br>Has not attain'd his noon. <br>Stay, stay,<br>Until the hasting day<br>Has run<br>But to the even-song;<br>And, having pray'd together, we<br>Will go with you along. <br><br>We have short time to stay, as you,<br>We have as short a spring;<br>As quick a growth to meet decay,<br>As you, or anything. <br>We die<br>As your hours do, and dry<br>Away,<br>Like to the summer's rain;<br>Or as the pearls of morning's dew,<br>Ne'er to be found again. ",
"After The Winter" : "Some day, when trees have shed their leaves<br>And against the morning's white<br>The shivering birds beneath the eaves<br>Have sheltered for the night,<br>We'll turn our faces southward, love,<br>Toward the summer isle<br>Where bamboos spire the shafted grove<br>And wide-mouthed orchids smile. <br><br>And we will seek the quiet hill<br>Where towers the cotton tree,<br>And leaps the laughing crystal rill,<br>And works the droning bee. <br>And we will build a cottage there<br>Beside an open glade,<br>With black-ribbed blue-bells blowing near,<br>And ferns that never fade. ",
"More Than Enough" : "The first lily of June opens its red mouth. <br>All over the sand road where we walk<br>multiflora rose climbs trees cascading<br>white or pink blossoms, simple, intense<br>the scene drifting like colored mist. <br><br>The arrowhead is spreading its creamy<br>clumps of flower and the blackberries<br>are blooming in the thickets. Season of<br>joy for the bee. The green will never<br>again be so green, so purely and lushly<br><br>new, grass lifting its wheaty seedheads<br>into the wind. Rich fresh wine<br>of June, we stagger into you smeared<br>with pollen, overcome as the turtle<br>laying her eggs in roadside sand.",
"Spring, the sweet spring" : "Spring, the sweet spring, is the year's pleasant king,<br>Then blooms each thing, then maids dance in a ring,<br>Cold doth not sting, the pretty birds do sing:<br>Cuckoo, jug-jug, pu-we, to-witta-woo!<br><br>The palm and may make country houses gay,<br>Lambs frisk and play, the shepherds pipe all day,<br>And we hear aye birds tune this merry lay:<br>Cuckoo, jug-jug, pu-we, to-witta-woo!<br><br>The fields breathe sweet, the daisies kiss our feet,<br>Young lovers meet, old wives a-sunning sit,<br>In every street these tunes our ears do greet:<br>Cuckoo, jug-jug, pu-we, to witta-woo!<br>Spring, the sweet spring!",
"To My Dear and Loving Husband" : "If ever two were one, then surely we. <br>If ever man were loved by wife, then thee. <br>If ever wife was happy in a man,<br>Compare with me, ye women, if you can. <br>I prize thy love more than whole mines of gold,<br>Or all the riches that the East doth hold. <br>My love is such that rivers cannot quench,<br>Nor ought but love from thee give recompense. <br>Thy love is such I can no way repay;<br>The heavens reward thee manifold, I pray. <br>Then while we live, in love let's so persever,<br>That when we live no more, we may live ever.",
"Take all my loves, my love, yea, take them all":"Take all my loves, my love, yea, take them all:<br>What hast thou then more than thou hadst before?<br>No love, my love, that thou mayst true love call-<br>All mine was thine before thou hadst this more. <br>Then if for my love thou my love receivest,<br>I cannot blame thee for my love thou usest;<br>But yet be blamed if thou this self deceivest<br>By wilful taste of what thyself refusest. <br>I do forgive thy robb'ry, gentle thief,<br>Although thou steal thee all my poverty;<br>And yet love knows it is a greater grief<br>To bear love's wrong than hate's known injury. <br>Lascivious grace, in whom all ill well shows,<br>Kill me with spites, yet we must not be foes.",
"Since brass, nor stone, nor earth, nor boundless sea":"Since brass, nor stone, nor earth, nor boundless sea<br>But sad mortality o'er-sways their power,<br>How with this rage shall beauty hold a plea,<br>Whose action is no stronger than a flower?<br>O, how shall summer's honey breath hold out<br>Against the wrackful siege of batt'ring days,<br>When rocks impregnable are not so stout,<br>Nor gates of steel so strong, but time decays?<br>O fearful meditation! where, alack,<br>Shall time's best jewel from time's chest lie hid?<br>Or what strong hand can hold his swift foot back?<br>Or who his spoil of beauty can forbid?<br>O, none, unless this miracle have might,<br>That in black ink my love may still shine bright.",
"Drink to me only with thine eyes":"Drink to me only with thine eyes,<br>And I will pledge with mine;<br>Or leave a kiss but in the cup,<br>And I'll not look for wine. <br>The thirst that from the soul doth rise<br>Doth ask a drink divine;<br>But might I of Jove's nectar sup,<br>I would not change for thine. <br><br>I sent thee late a rosy wreath,<br>Not so much honouring thee<br>As giving it a hope, that there<br>It could not withered be. <br>But thou thereon didst only breathe,<br>And sent'st it back to me;<br>Since when it grows, and smells, I swear,<br>Not of itself, but thee.",
"Poem for My Love":"How do we come to be here next to each other<br>in the night<br>Where are the stars that show us to our love<br>inevitable<br>Outside the leaves flame usual in darkness<br>and the rain<br>falls cool and blessed on the holy flesh<br>the black men waiting on the corner for<br>a womanly mirage<br>I am amazed by peace<br>It is this possibility of you<br>asleep<br>and breathing in the quiet air",
"If Roses grow in Heaven":"If Roses grow in Heaven<br>Lord, please pick a bunch for me. <br>Place them in my Mother's arms<br>and tell her they're from me. <br><br>Tell her that I love her and miss her,<br>and when she turns to smile,<br>place a kiss upon her cheek<br>and hold her for awhile. <br><br>Because remembering her is easy,<br>I do it every day,<br>but there's an ache within my heart<br>that will never go away.",
"Death, be not proud":"Death, be not proud, though some have called thee<br>Mighty and dreadful, for thou art not so;<br>For those whom thou think'st thou dost overthrow<br>Die not, poor Death, nor yet canst thou kill me. <br>From rest and sleep, which but thy pictures be,<br>Much pleasure; then from thee much more must flow,<br>And soonest our best men with thee do go,<br>Rest of their bones, and soul's delivery. <br>Thou art slave to fate, chance, kings, and desperate men,<br>And dost with poison, war, and sickness dwell,<br>And poppy or charms can make us sleep as well<br>And better than thy stroke; why swell'st thou then?<br>One short sleep past, we wake eternally<br>And death shall be no more; Death, thou shalt die.",
"Do Not Stand at My Grave and Weep":"Do not stand<br>By my grave, and weep. <br>I am not there,<br>I do not sleep-<br>I am the thousand winds that blow<br>I am the diamond glints in snow<br>I am the sunlight on ripened grain,<br>I am the gentle, autumn rain. <br>As you awake with morning’s hush,<br>I am the swift, up-flinging rush<br>Of quiet birds in circling flight,<br>I am the day transcending night. <br>Do not stand<br>By my grave, and cry-<br>I am not there,<br>I did not die.",
"The Mower":"The mower stalled, twice; kneeling, I found<br>A hedgehog jammed up against the blades,<br>Killed. It had been in the long grass. <br><br>I had seen it before, and even fed it, once. <br>Now I had mauled its unobtrusive world<br>Unmendably. Burial was no help:<br><br>Next morning I got up and it did not. <br>The first day after a death, the new absence<br>Is always the same; we should be careful<br><br>Of each other, we should be kind<br>While there is still time.",
"Remember":"Remember me when I am gone away,<br>Gone far away into the silent land;<br>When you can no more hold me by the hand,<br>Nor I half turn to go yet turning stay. <br>Remember me when no more day by day<br>You tell me of our future that you plann'd:<br>Only remember me; you understand<br>It will be late to counsel then or pray. <br>Yet if you should forget me for a while<br>And afterwards remember, do not grieve:<br>For if the darkness and corruption leave<br>A vestige of the thoughts that once I had,<br>Better by far you should forget and smile<br>Than that you should remember and be sad.",
"Ozymandias":"I met a traveller from an antique land,<br>Who said-Two vast and trunkless legs of stone<br>Stand in the desert. Near them, on the sand,<br>Half sunk a shattered visage lies, whose frown,<br>And wrinkled lip, and sneer of cold command,<br>Tell that its sculptor well those passions read<br>Which yet survive, stamped on these lifeless things,<br>The hand that mocked them, and the heart that fed;<br>And on the pedestal, these words appear:<br>My name is Ozymandias, King of Kings;<br>Look on my Works, ye Mighty, and despair!<br>Nothing beside remains. Round the decay<br>Of that colossal Wreck, boundless and bare<br>The lone and level sands stretch far away.",
"A Prayer for Travelers":"May the road rise up to meet you. <br>May the wind be always at your back. <br>May the sun shine warm upon your face;<br>The rains fall soft upon your fields. <br>And until we meet again,<br>May God hold you in the palm of His hand.",
"Song of the Open Road":"Afoot and light-hearted I take to the open road,<br>Healthy, free, the world before me,<br>The long brown path before me leading me wherever I choose. <br><br>Henceforth I ask not good-fortune, I myself am good-fortune,<br>Henceforth I whimper no more, postpone no more, need nothing,<br>Done with indoor complaints, libraries, querulous criticisms,<br>Strong and content I travel the open road.",
"Freedom":"Give me the long, straight road before me,<br>A clear, cold day with a nipping air,<br>Tall, bare trees to run on beside me,<br>A heart that is light and free from care. <br>Then let me go! I care not whither<br>My feet may lead, for my spirit shall be<br>Free as the brook that flows to the river,<br>Free as the river that flows to the sea.",
"P.S. I Love You":"Twenty years from now<br>You'll be more disappointed<br>By the things you didn't do<br>Than by the ones you did do. <br>So throw off the bowlines. <br>Sail away from the harbor. <br>Catch the trade winds in your sails. <br>Explore. Dream. Discover."
};
const listaTitluri = {
"spring":
  ["Daisy Time" , "To Daffodils" , "After The Winter", "More Than Enough", "Spring, the sweet spring"],
"love":
  ["To My Dear and Loving Husband" , "Take all my loves, my love, yea, take them all" , "Since brass, nor stone, nor earth, nor boundless sea","Drink to me only with thine eyes","Poem for My Love"],
"history":
  ["Ozymandias" , "A Prayer for Travelers" , "Song of the Open Road","Freedom","P.S. I Love You"],
"death":
  ["If Roses grow in Heaven" , "Death, be not proud" , "Do Not Stand at My Grave and Weep","The Mower","Remember"]
};